model:
  fusion:
    geometry_dim: 512
    hidden_dim: 4096
    visual_dim: 1024
  geometry:
    change_threshold: 0.1
    freeze: true
    name: naver/DUSt3R_ViTLarge_BaseDecoder_512_linear
  hidden_dim: 4096
  num_process_stages: 8
  verifier:
    hidden_dim: 512
  vlm:
    freeze: true
    lora:
      alpha: 32
      enabled: true
      r: 16
    name: /workspace/.hf_home/hub/LLaVA-NeXT-Video-7B
    token: geocar
